<?xml version='1.0' encoding='UTF-8'?><!-- Published by XML-WS Runtime (https://github.com/eclipse-ee4j/metro-jax-ws). Runtime's version is Eclipse Metro/4.0.4.payara-p1 (FISH-10142-Metro-4.0.4-fa01c0b; 2025-07-11T17:44:37+0100) XMLWS-Impl/4.0.3 XMLWS-API/4.0.2 XMLB-Impl/4.0.5 XMLB-API/4.0.2 git-revision#fa01c0b. --><xs:schema xmlns:tns="http://ws.monster.edu.ec/" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" targetNamespace="http://ws.monster.edu.ec/">

<xs:element name="comprarBoleto" type="tns:comprarBoleto"/>

<xs:element name="comprarBoletoResponse" type="tns:comprarBoletoResponse"/>

<xs:element name="decrementarDisponibilidad" type="tns:decrementarDisponibilidad"/>

<xs:element name="decrementarDisponibilidadResponse" type="tns:decrementarDisponibilidadResponse"/>

<xs:element name="obtenerLocalidades" type="tns:obtenerLocalidades"/>

<xs:element name="obtenerLocalidadesResponse" type="tns:obtenerLocalidadesResponse"/>

<xs:element name="obtenerPartido" type="tns:obtenerPartido"/>

<xs:element name="obtenerPartidoResponse" type="tns:obtenerPartidoResponse"/>

<xs:element name="obtenerPartidosDisponibles" type="tns:obtenerPartidosDisponibles"/>

<xs:element name="obtenerPartidosDisponiblesResponse" type="tns:obtenerPartidosDisponiblesResponse"/>

<xs:element name="obtenerResumenVentas" type="tns:obtenerResumenVentas"/>

<xs:element name="obtenerResumenVentasResponse" type="tns:obtenerResumenVentasResponse"/>

<xs:complexType name="comprarBoleto">
<xs:sequence>
<xs:element name="codigoPartido" type="xs:int"/>
<xs:element name="nombreCliente" type="xs:string" minOccurs="0"/>
<xs:element name="codigoLocalidad" type="xs:string" minOccurs="0"/>
<xs:element name="idLocalidad" type="xs:int"/>
<xs:element name="cantidad" type="xs:int"/>
<xs:element name="precioUnitario" type="xs:double"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="comprarBoletoResponse">
<xs:sequence>
<xs:element name="return" type="tns:factura" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="factura">
<xs:sequence>
<xs:element name="codigoPartido" type="xs:int"/>
<xs:element name="detalles" type="tns:detalleFactura" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
<xs:element name="fecha" type="xs:string" minOccurs="0"/>
<xs:element name="id" type="xs:int"/>
<xs:element name="iva" type="xs:double"/>
<xs:element name="nombreCliente" type="xs:string" minOccurs="0"/>
<xs:element name="subtotal" type="xs:double"/>
<xs:element name="total" type="xs:double"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="detalleFactura">
<xs:sequence>
<xs:element name="cantidad" type="xs:int"/>
<xs:element name="codigoLocalidad" type="xs:string" minOccurs="0"/>
<xs:element name="codigoPartido" type="xs:int"/>
<xs:element name="id" type="xs:int"/>
<xs:element name="idFactura" type="xs:int"/>
<xs:element name="precioUnitario" type="xs:double"/>
<xs:element name="subtotal" type="xs:double"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="obtenerLocalidades">
<xs:sequence>
<xs:element name="codigoPartido" type="xs:int"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="obtenerLocalidadesResponse">
<xs:sequence>
<xs:element name="return" type="tns:localidadPartido" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="localidadPartido">
<xs:sequence>
<xs:element name="codigoLocalidad" type="xs:string" minOccurs="0"/>
<xs:element name="codigoPartido" type="xs:int"/>
<xs:element name="disponibilidad" type="xs:int"/>
<xs:element name="id" type="xs:int"/>
<xs:element name="precio" type="xs:double"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="obtenerPartido">
<xs:sequence>
<xs:element name="codigoPartido" type="xs:int"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="obtenerPartidoResponse">
<xs:sequence>
<xs:element name="return" type="tns:partidoFutbol" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="partidoFutbol">
<xs:sequence>
<xs:element name="codigo" type="xs:int"/>
<xs:element name="equipoLocal" type="xs:string" minOccurs="0"/>
<xs:element name="equipoVisita" type="xs:string" minOccurs="0"/>
<xs:element name="fecha" type="xs:string" minOccurs="0"/>
<xs:element name="lugar" type="xs:string" minOccurs="0"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="decrementarDisponibilidad">
<xs:sequence>
<xs:element name="idLocalidad" type="xs:int"/>
<xs:element name="cantidad" type="xs:int"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="decrementarDisponibilidadResponse">
<xs:sequence>
<xs:element name="return" type="xs:boolean"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="obtenerResumenVentas">
<xs:sequence>
<xs:element name="codigoPartido" type="xs:int"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="obtenerResumenVentasResponse">
<xs:sequence>
<xs:element name="return" type="tns:resumenVenta" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="resumenVenta">
<xs:sequence>
<xs:element name="codigoLocalidad" type="xs:string" minOccurs="0"/>
<xs:element name="totalRecaudado" type="xs:double"/>
<xs:element name="vendidos" type="xs:int"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="obtenerPartidosDisponibles">
<xs:sequence/>
</xs:complexType>

<xs:complexType name="obtenerPartidosDisponiblesResponse">
<xs:sequence>
<xs:element name="return" type="tns:partidoFutbol" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
</xs:schema>