//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONUNI_SOAP_DOTNET_CLICON_G09.MiServicio
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CONUNI_SOAP_DOTNET_CLICON_G09.MiServicio.WSConversion")]
    public interface WSConversion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/login", ReplyAction="http://tempuri.org/WSConversion/loginResponse")]
        bool login(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/login", ReplyAction="http://tempuri.org/WSConversion/loginResponse")]
        System.Threading.Tasks.Task<bool> loginAsync(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/celsiusAFahrenheit", ReplyAction="http://tempuri.org/WSConversion/celsiusAFahrenheitResponse")]
        double celsiusAFahrenheit(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/celsiusAFahrenheit", ReplyAction="http://tempuri.org/WSConversion/celsiusAFahrenheitResponse")]
        System.Threading.Tasks.Task<double> celsiusAFahrenheitAsync(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/fahrenheitACelsius", ReplyAction="http://tempuri.org/WSConversion/fahrenheitACelsiusResponse")]
        double fahrenheitACelsius(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/fahrenheitACelsius", ReplyAction="http://tempuri.org/WSConversion/fahrenheitACelsiusResponse")]
        System.Threading.Tasks.Task<double> fahrenheitACelsiusAsync(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/celsiusAKelvin", ReplyAction="http://tempuri.org/WSConversion/celsiusAKelvinResponse")]
        double celsiusAKelvin(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/celsiusAKelvin", ReplyAction="http://tempuri.org/WSConversion/celsiusAKelvinResponse")]
        System.Threading.Tasks.Task<double> celsiusAKelvinAsync(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/kelvinACelsius", ReplyAction="http://tempuri.org/WSConversion/kelvinACelsiusResponse")]
        double kelvinACelsius(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/kelvinACelsius", ReplyAction="http://tempuri.org/WSConversion/kelvinACelsiusResponse")]
        System.Threading.Tasks.Task<double> kelvinACelsiusAsync(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/fahrenheitAKelvin", ReplyAction="http://tempuri.org/WSConversion/fahrenheitAKelvinResponse")]
        double fahrenheitAKelvin(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/fahrenheitAKelvin", ReplyAction="http://tempuri.org/WSConversion/fahrenheitAKelvinResponse")]
        System.Threading.Tasks.Task<double> fahrenheitAKelvinAsync(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/kelvinAFahrenheit", ReplyAction="http://tempuri.org/WSConversion/kelvinAFahrenheitResponse")]
        double kelvinAFahrenheit(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/kelvinAFahrenheit", ReplyAction="http://tempuri.org/WSConversion/kelvinAFahrenheitResponse")]
        System.Threading.Tasks.Task<double> kelvinAFahrenheitAsync(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/metrosAPies", ReplyAction="http://tempuri.org/WSConversion/metrosAPiesResponse")]
        double metrosAPies(double metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/metrosAPies", ReplyAction="http://tempuri.org/WSConversion/metrosAPiesResponse")]
        System.Threading.Tasks.Task<double> metrosAPiesAsync(double metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/piesAMetros", ReplyAction="http://tempuri.org/WSConversion/piesAMetrosResponse")]
        double piesAMetros(double pies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/piesAMetros", ReplyAction="http://tempuri.org/WSConversion/piesAMetrosResponse")]
        System.Threading.Tasks.Task<double> piesAMetrosAsync(double pies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/metrosAPulgadas", ReplyAction="http://tempuri.org/WSConversion/metrosAPulgadasResponse")]
        double metrosAPulgadas(double metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/metrosAPulgadas", ReplyAction="http://tempuri.org/WSConversion/metrosAPulgadasResponse")]
        System.Threading.Tasks.Task<double> metrosAPulgadasAsync(double metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/pulgadasAMetros", ReplyAction="http://tempuri.org/WSConversion/pulgadasAMetrosResponse")]
        double pulgadasAMetros(double pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/pulgadasAMetros", ReplyAction="http://tempuri.org/WSConversion/pulgadasAMetrosResponse")]
        System.Threading.Tasks.Task<double> pulgadasAMetrosAsync(double pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/kilometrosAMillas", ReplyAction="http://tempuri.org/WSConversion/kilometrosAMillasResponse")]
        double kilometrosAMillas(double kilometros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/kilometrosAMillas", ReplyAction="http://tempuri.org/WSConversion/kilometrosAMillasResponse")]
        System.Threading.Tasks.Task<double> kilometrosAMillasAsync(double kilometros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/millasAKilometros", ReplyAction="http://tempuri.org/WSConversion/millasAKilometrosResponse")]
        double millasAKilometros(double millas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/millasAKilometros", ReplyAction="http://tempuri.org/WSConversion/millasAKilometrosResponse")]
        System.Threading.Tasks.Task<double> millasAKilometrosAsync(double millas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/kilogramosALibras", ReplyAction="http://tempuri.org/WSConversion/kilogramosALibrasResponse")]
        double kilogramosALibras(double kilogramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/kilogramosALibras", ReplyAction="http://tempuri.org/WSConversion/kilogramosALibrasResponse")]
        System.Threading.Tasks.Task<double> kilogramosALibrasAsync(double kilogramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/librasAKilogramos", ReplyAction="http://tempuri.org/WSConversion/librasAKilogramosResponse")]
        double librasAKilogramos(double libras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/librasAKilogramos", ReplyAction="http://tempuri.org/WSConversion/librasAKilogramosResponse")]
        System.Threading.Tasks.Task<double> librasAKilogramosAsync(double libras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/gramosAOnzas", ReplyAction="http://tempuri.org/WSConversion/gramosAOnzasResponse")]
        double gramosAOnzas(double gramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/gramosAOnzas", ReplyAction="http://tempuri.org/WSConversion/gramosAOnzasResponse")]
        System.Threading.Tasks.Task<double> gramosAOnzasAsync(double gramos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/onzasAGramos", ReplyAction="http://tempuri.org/WSConversion/onzasAGramosResponse")]
        double onzasAGramos(double onzas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/onzasAGramos", ReplyAction="http://tempuri.org/WSConversion/onzasAGramosResponse")]
        System.Threading.Tasks.Task<double> onzasAGramosAsync(double onzas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/litrosAGalones", ReplyAction="http://tempuri.org/WSConversion/litrosAGalonesResponse")]
        double litrosAGalones(double litros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/litrosAGalones", ReplyAction="http://tempuri.org/WSConversion/litrosAGalonesResponse")]
        System.Threading.Tasks.Task<double> litrosAGalonesAsync(double litros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/galonesALitros", ReplyAction="http://tempuri.org/WSConversion/galonesALitrosResponse")]
        double galonesALitros(double galones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/galonesALitros", ReplyAction="http://tempuri.org/WSConversion/galonesALitrosResponse")]
        System.Threading.Tasks.Task<double> galonesALitrosAsync(double galones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/mililitrosAOnzasFluidas", ReplyAction="http://tempuri.org/WSConversion/mililitrosAOnzasFluidasResponse")]
        double mililitrosAOnzasFluidas(double mililitros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/mililitrosAOnzasFluidas", ReplyAction="http://tempuri.org/WSConversion/mililitrosAOnzasFluidasResponse")]
        System.Threading.Tasks.Task<double> mililitrosAOnzasFluidasAsync(double mililitros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/onzasFluidasAMililitros", ReplyAction="http://tempuri.org/WSConversion/onzasFluidasAMililitrosResponse")]
        double onzasFluidasAMililitros(double onzasFluidas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/onzasFluidasAMililitros", ReplyAction="http://tempuri.org/WSConversion/onzasFluidasAMililitrosResponse")]
        System.Threading.Tasks.Task<double> onzasFluidasAMililitrosAsync(double onzasFluidas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/metrosCuadradosAPiesCuadrados", ReplyAction="http://tempuri.org/WSConversion/metrosCuadradosAPiesCuadradosResponse")]
        double metrosCuadradosAPiesCuadrados(double metrosCuadrados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/metrosCuadradosAPiesCuadrados", ReplyAction="http://tempuri.org/WSConversion/metrosCuadradosAPiesCuadradosResponse")]
        System.Threading.Tasks.Task<double> metrosCuadradosAPiesCuadradosAsync(double metrosCuadrados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/piesCuadradosAMetrosCuadrados", ReplyAction="http://tempuri.org/WSConversion/piesCuadradosAMetrosCuadradosResponse")]
        double piesCuadradosAMetrosCuadrados(double piesCuadrados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/piesCuadradosAMetrosCuadrados", ReplyAction="http://tempuri.org/WSConversion/piesCuadradosAMetrosCuadradosResponse")]
        System.Threading.Tasks.Task<double> piesCuadradosAMetrosCuadradosAsync(double piesCuadrados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/hectareasAAcres", ReplyAction="http://tempuri.org/WSConversion/hectareasAAcresResponse")]
        double hectareasAAcres(double hectareas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/hectareasAAcres", ReplyAction="http://tempuri.org/WSConversion/hectareasAAcresResponse")]
        System.Threading.Tasks.Task<double> hectareasAAcresAsync(double hectareas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/acresAHectareas", ReplyAction="http://tempuri.org/WSConversion/acresAHectareasResponse")]
        double acresAHectareas(double acres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSConversion/acresAHectareas", ReplyAction="http://tempuri.org/WSConversion/acresAHectareasResponse")]
        System.Threading.Tasks.Task<double> acresAHectareasAsync(double acres);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSConversionChannel : CONUNI_SOAP_DOTNET_CLICON_G09.MiServicio.WSConversion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSConversionClient : System.ServiceModel.ClientBase<CONUNI_SOAP_DOTNET_CLICON_G09.MiServicio.WSConversion>, CONUNI_SOAP_DOTNET_CLICON_G09.MiServicio.WSConversion
    {
        
        public WSConversionClient()
        {
        }
        
        public WSConversionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WSConversionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WSConversionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WSConversionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool login(string usuario, string contrasena)
        {
            return base.Channel.login(usuario, contrasena);
        }
        
        public System.Threading.Tasks.Task<bool> loginAsync(string usuario, string contrasena)
        {
            return base.Channel.loginAsync(usuario, contrasena);
        }
        
        public double celsiusAFahrenheit(double celsius)
        {
            return base.Channel.celsiusAFahrenheit(celsius);
        }
        
        public System.Threading.Tasks.Task<double> celsiusAFahrenheitAsync(double celsius)
        {
            return base.Channel.celsiusAFahrenheitAsync(celsius);
        }
        
        public double fahrenheitACelsius(double fahrenheit)
        {
            return base.Channel.fahrenheitACelsius(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> fahrenheitACelsiusAsync(double fahrenheit)
        {
            return base.Channel.fahrenheitACelsiusAsync(fahrenheit);
        }
        
        public double celsiusAKelvin(double celsius)
        {
            return base.Channel.celsiusAKelvin(celsius);
        }
        
        public System.Threading.Tasks.Task<double> celsiusAKelvinAsync(double celsius)
        {
            return base.Channel.celsiusAKelvinAsync(celsius);
        }
        
        public double kelvinACelsius(double kelvin)
        {
            return base.Channel.kelvinACelsius(kelvin);
        }
        
        public System.Threading.Tasks.Task<double> kelvinACelsiusAsync(double kelvin)
        {
            return base.Channel.kelvinACelsiusAsync(kelvin);
        }
        
        public double fahrenheitAKelvin(double fahrenheit)
        {
            return base.Channel.fahrenheitAKelvin(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> fahrenheitAKelvinAsync(double fahrenheit)
        {
            return base.Channel.fahrenheitAKelvinAsync(fahrenheit);
        }
        
        public double kelvinAFahrenheit(double kelvin)
        {
            return base.Channel.kelvinAFahrenheit(kelvin);
        }
        
        public System.Threading.Tasks.Task<double> kelvinAFahrenheitAsync(double kelvin)
        {
            return base.Channel.kelvinAFahrenheitAsync(kelvin);
        }
        
        public double metrosAPies(double metros)
        {
            return base.Channel.metrosAPies(metros);
        }
        
        public System.Threading.Tasks.Task<double> metrosAPiesAsync(double metros)
        {
            return base.Channel.metrosAPiesAsync(metros);
        }
        
        public double piesAMetros(double pies)
        {
            return base.Channel.piesAMetros(pies);
        }
        
        public System.Threading.Tasks.Task<double> piesAMetrosAsync(double pies)
        {
            return base.Channel.piesAMetrosAsync(pies);
        }
        
        public double metrosAPulgadas(double metros)
        {
            return base.Channel.metrosAPulgadas(metros);
        }
        
        public System.Threading.Tasks.Task<double> metrosAPulgadasAsync(double metros)
        {
            return base.Channel.metrosAPulgadasAsync(metros);
        }
        
        public double pulgadasAMetros(double pulgadas)
        {
            return base.Channel.pulgadasAMetros(pulgadas);
        }
        
        public System.Threading.Tasks.Task<double> pulgadasAMetrosAsync(double pulgadas)
        {
            return base.Channel.pulgadasAMetrosAsync(pulgadas);
        }
        
        public double kilometrosAMillas(double kilometros)
        {
            return base.Channel.kilometrosAMillas(kilometros);
        }
        
        public System.Threading.Tasks.Task<double> kilometrosAMillasAsync(double kilometros)
        {
            return base.Channel.kilometrosAMillasAsync(kilometros);
        }
        
        public double millasAKilometros(double millas)
        {
            return base.Channel.millasAKilometros(millas);
        }
        
        public System.Threading.Tasks.Task<double> millasAKilometrosAsync(double millas)
        {
            return base.Channel.millasAKilometrosAsync(millas);
        }
        
        public double kilogramosALibras(double kilogramos)
        {
            return base.Channel.kilogramosALibras(kilogramos);
        }
        
        public System.Threading.Tasks.Task<double> kilogramosALibrasAsync(double kilogramos)
        {
            return base.Channel.kilogramosALibrasAsync(kilogramos);
        }
        
        public double librasAKilogramos(double libras)
        {
            return base.Channel.librasAKilogramos(libras);
        }
        
        public System.Threading.Tasks.Task<double> librasAKilogramosAsync(double libras)
        {
            return base.Channel.librasAKilogramosAsync(libras);
        }
        
        public double gramosAOnzas(double gramos)
        {
            return base.Channel.gramosAOnzas(gramos);
        }
        
        public System.Threading.Tasks.Task<double> gramosAOnzasAsync(double gramos)
        {
            return base.Channel.gramosAOnzasAsync(gramos);
        }
        
        public double onzasAGramos(double onzas)
        {
            return base.Channel.onzasAGramos(onzas);
        }
        
        public System.Threading.Tasks.Task<double> onzasAGramosAsync(double onzas)
        {
            return base.Channel.onzasAGramosAsync(onzas);
        }
        
        public double litrosAGalones(double litros)
        {
            return base.Channel.litrosAGalones(litros);
        }
        
        public System.Threading.Tasks.Task<double> litrosAGalonesAsync(double litros)
        {
            return base.Channel.litrosAGalonesAsync(litros);
        }
        
        public double galonesALitros(double galones)
        {
            return base.Channel.galonesALitros(galones);
        }
        
        public System.Threading.Tasks.Task<double> galonesALitrosAsync(double galones)
        {
            return base.Channel.galonesALitrosAsync(galones);
        }
        
        public double mililitrosAOnzasFluidas(double mililitros)
        {
            return base.Channel.mililitrosAOnzasFluidas(mililitros);
        }
        
        public System.Threading.Tasks.Task<double> mililitrosAOnzasFluidasAsync(double mililitros)
        {
            return base.Channel.mililitrosAOnzasFluidasAsync(mililitros);
        }
        
        public double onzasFluidasAMililitros(double onzasFluidas)
        {
            return base.Channel.onzasFluidasAMililitros(onzasFluidas);
        }
        
        public System.Threading.Tasks.Task<double> onzasFluidasAMililitrosAsync(double onzasFluidas)
        {
            return base.Channel.onzasFluidasAMililitrosAsync(onzasFluidas);
        }
        
        public double metrosCuadradosAPiesCuadrados(double metrosCuadrados)
        {
            return base.Channel.metrosCuadradosAPiesCuadrados(metrosCuadrados);
        }
        
        public System.Threading.Tasks.Task<double> metrosCuadradosAPiesCuadradosAsync(double metrosCuadrados)
        {
            return base.Channel.metrosCuadradosAPiesCuadradosAsync(metrosCuadrados);
        }
        
        public double piesCuadradosAMetrosCuadrados(double piesCuadrados)
        {
            return base.Channel.piesCuadradosAMetrosCuadrados(piesCuadrados);
        }
        
        public System.Threading.Tasks.Task<double> piesCuadradosAMetrosCuadradosAsync(double piesCuadrados)
        {
            return base.Channel.piesCuadradosAMetrosCuadradosAsync(piesCuadrados);
        }
        
        public double hectareasAAcres(double hectareas)
        {
            return base.Channel.hectareasAAcres(hectareas);
        }
        
        public System.Threading.Tasks.Task<double> hectareasAAcresAsync(double hectareas)
        {
            return base.Channel.hectareasAAcresAsync(hectareas);
        }
        
        public double acresAHectareas(double acres)
        {
            return base.Channel.acresAHectareas(acres);
        }
        
        public System.Threading.Tasks.Task<double> acresAHectareasAsync(double acres)
        {
            return base.Channel.acresAHectareasAsync(acres);
        }
    }
}
